apiVersion: v1
kind: Secret
metadata:
  name: guestbook-secrets
type: Opaque
stringData:
  redishost: "redis-master"
  redisport: "6379"
  redispass: "c3RyMG5nLXA0NTVzdzByZA=="
  redismasterport: "6379"
